# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          The Jekyll Butler
description:      Base theme for Jekyll themes by @mdo.
url:              http://capecodcid.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

link_list:
  About: '/about'
  Archive: '/archive'
  


author:
  name:           Andrew Hartnett
  bio:            "Scientist & Educator"
  email:          a.t.hartnett@gmail.com
  twitter:        hartnett_andrew        
  github:         capecodcid     

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
