# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          The Jekyll Butler
description:      Base theme for Jekyll themes by @mdo.
url:              http://capecodcid.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

author:
  name:           Mark Otto
  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
