# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            PYW-WYP
tagline:          Science and Education
description:      Personal webpage of Andrew Hartnett.
#url:              http://capecodcid.github.io
baseurl:          /
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

links:
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Archive
    url: /archive
  - title: Couzin Lab
    url: http://icouzin.princeton.edu/
    external: true


author:
  name:           Andrew Hartnett
  bio:            "Scientist & Educator"
  email:          a.t.hartnett@gmail.com
  twitter:        hartnett_andrew        
  github:         capecodcid     

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/capecodcid/capecodcid.io
